language:
  - python

python:
  - 3.6

sudo: false

env:
  matrix:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10

before_install:
  - curl -LOk https://github.com/divio/djangocms-boilerplate-html5/archive/master.tar.gz
  - tar -xzf master.tar.gz
  - mv -n djangocms-boilerplate-html5-master/{*,.*} .

install:
  - pip install -r requirements.txt
  - python manage.py migrate --noinput
  - python manage.py loaddata data.json

script:
  - echo 'Project build successfull'
