language:
  - "python"

python:
  - "2.7"

services:
  - "postgresql"

env:
  - "DJANGO=1.6"
  - "DJANGO=1.7"

before_install:
  - "gem install scss-lint"
  - "npm install -g npm"
  - "psql -c 'CREATE DATABASE djangocms_demo_local;' -U postgres"

install:
  - "pip install -r requirements.txt"
  - "python src/manage.py migrate --noinput"

before_script:
  - "npm install -g gulp"
  - "npm install -g codeclimate-test-reporter"
  - "npm install"

after_script:
  - "codeclimate < tests/coverage/**/lcov.info"

script:
  - "echo 'Project build successfull'"
  - "gulp tests"
