language:
  - "python"

python:
  - "2.7"

services:
  - "postgresql"

env:
  matrix:
    - "DJANGO=1.6"
    - "DJANGO=1.7"
  global:
    - secure: Ar3k6AtGWdnvut/wcsZdZnGCqu1C2KX8hl11GTpj5UfCz4yvworjHk1Vpeka5n0OC4ZaMmy9/0dtKGB50RzX1hO9UHIr88M1maddBYY/Let7m5NeWfOAODUalkU/mDdktfH4MJzBKuCKNeZec3Vjf3rZGxwZevOlO8NUOvhcX9s2rJ9vzlYuTbODGreZnotwnixVM9jpWgoKgLQMdOsRUagxi6SvOVd6S+FLJp/5XspT1VzXJHdXMz/sPVS3mL0hRuqMNcW+0szRlwzeNmV4ufF979fTCEvzvqhl1w2J7e08DRZ6vU5SNm2qbluun8F0wdbyZRBcdyQvsMNZtLf6/GhMJ05ZKP2n90wOpbNkC6HsX3OOm7ePn4kTiRAKAvnHLtgDxdNvkF/oaL3knE9ukKr0wo1N0pnAJpVuDu249YDO+80tHDvjK1kH0Yc5vsSUJ1vcyZJ+EA0ZAh/2Q5FmvVgxA3fOxpNYDkCT0KKqJrvGWlLMV0MgxQ5CyjevjJLWptJyAH9kDXvmXbDLjEtQVMRoS9YjhApFcgnAKhXSYcg5+/njJexYdqRV7XsKlBw1bFjZ1rTU2oVT1JUqSn7/4qRFdohpRo4c/PKNFoy0DoH9MvkomGrQYlnLIFvJEjcDzOF2meXKV0A4nmPV9ao9vCTk8ivsLSHTTXKQKoANVhs=
    - secure: pMP64u6qpd2Ew4Y0QCOK0oQY7xOeJI3TVz3HJox6zGdG47Y/yiaMMJxs3f0EIZZpHtGdts3vcaLeWkKlylXyC3q3bd+loc7nl2B52+v4yKj3xFLqUcbViUARZH1p6gSnjVg5LVI04MaUphwHbn+CxMF8iplj0yP9Opk92UgO/ZZx21U5RV8rPryeTmfp5hVEuoMDUOaL0usPYJl9Ef5pPFybGKfUfcmu3qwxTl5nsrJaxMyiJBAwVEblfNzLnDabNN3PU/mSDMzofumjGSyfMdbqmOtRrooayb8q0QlaDTeEFt6C6rCCD6FpnL3NHTQFoi02Mh6sgbmjbC+sn2rpU89+7luagqKQy6cmWGpUB4fQYk4jZsaetXaSfcGJ6GVkuq+sz6mME5vo3LA7a0DcHaN4AIqds8WYaxoyqVUGWext7gdamPF0QLsTTUf7bME7kpiusl/m3SDIRal8f8PbXJyejQJvHKBraZmkvfbJDQ1QxN+BLS4SxtfmED2rIAexSKYgVai6FRETFaqfDQDtQ/QovtIHqb29n+pGp26cGZ9/pJLoeDxwxEfTMU8QWpNFBXSOeselcB69TdyovKrkva0agok1m1oAMtWw6focjKn+ziC9gDRQCEl90qW8/yQsCBcEtF1AEn5rl3vwbEWWpAaa/Ao3pIPD+ZnJtZ82u8M=
    - secure: NXmqGud0TX6tzDZwg/RrKBgx556ZcwGDTQn7TGBpkJmbKp8tlqppDIsw9h/NbsZpvcZMiNhTC/11pxwA78NcU2EYDb3tdic3UF/F31o40porEg3BtjfdoniLAsiTesyGkBRL7DFvcDy1Z+4rfU7ZxzB4/e6kG7ox7xKBcKPLqjyQQZA21xZIEK3JFYBthZTormxTFsp8nSlF/KgCcVNhGj8vF9bXVvgLxtJefkLqYJUzUTs85fASr82dQFQ5fR2vDqBh4LRBpBu6BtgoiypNsvW8+4cGCU4+byPScBNrNepKnaPvGmXmsOjCWzlqx9G6uYqB/KGnvFNZrsAmJxhQV3k6BVZiJupesj4bNYsQKxR9Bsri2uhIQHLatGvouwrJETdAjYD2PXd8N/WvfLKwnMBM1eYldZJhY/pwGuw3sTUYangQtjHeqPPDlFjvgFbY3Yh4VWcRPVep2ySIcUmuvMCs5MlrM6A9X/SCieA2dIPD05uVj9f3zBFoT+XlLrDow/rROPTeMHnSzLWKo7G4gNV8BFrrBrAKFov9/N+zLC8Ifn5kJBwayztb52x3v5WhUeCxnFi3k8HduYrQunoayWZU64FQOTlKZOJc5G5AKmNo8wh9tchp0+Qv8zKMHkjO5/vcDmMl8djy3zvqjN7/k9n6Ls5+48E11FXTjJzrmBI=

before_install:
  - "gem install scss-lint"
  - "npm install -g npm"
  - "psql -c 'CREATE DATABASE djangocms_demo_local;' -U postgres"

install:
  - "pip install -r requirements.txt"
  - "python src/manage.py migrate --noinput"

before_script:
  - "npm install -g gulp"
  - "npm install -g codeclimate-test-reporter"
  - "npm install"

after_script:
  - "codeclimate < tests/coverage/**/lcov.info"

script:
  - "echo 'Project build successfull'"
  - "gulp tests"
  - "gulp tests:integration"
