language:
  - "python"

python:
  - "2.7"

services:
  - "postgresql"

env:
  - "DJANGO=1.6"
  - "DJANGO=1.7"

before_install:
  - "psql -c 'CREATE DATABASE djangocms_demo_local;' -U postgres"

install:
  - "pip install -r requirements.txt"
  - "python src/manage.py migrate --noinput"

script:
  - "echo 'Project build successfull'"
