web:
    build: .
    environment:
        - DB_HOST=postgres
    links:
        - postgres:postgres
    ports:
        - "8000:8000"
    volumes:
        - .:/project

postgres:
    image: postgres
    volumes_from:
        - data

data:
    image: postgres:latest
    volumes:
        - /var/lib/postgresql
